<a href="https://colab.research.google.com/github/neochen8806/AI_and_security_2020-new/blob/main/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 14.92 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [2]:
ls

examples/  sample_data/


In [4]:
cd examples

/content/examples


In [5]:
ls

AUTHORS     CONTRIBUTING.md  LICENSE    setup.py
CODEOWNERS  courses/         lite/      templates/
community/  __init__.py      README.md  tensorflow_examples/


In [7]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [12]:
import numpy as np
a = np.random.uniform(2,5,3)
a

array([2.84448263, 3.92726803, 2.12158167])

In [21]:
b = np.random.randn(2,5)
b


array([[-1.41472282, -0.02683593,  0.18505816, -2.02618771, -0.1652587 ],
       [-0.9276157 , -1.69920394,  0.9888771 ,  0.34058798, -1.09922559]])

In [23]:
b.data.shape

(2, 5)

In [16]:
data.dtype

dtype('float64')

In [25]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
import numpy as np
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [27]:
import numpy as np
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [28]:
import numpy as np
np.linspace(1., 4., 6) # start, end, num

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [29]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [30]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [31]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [32]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [33]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])